[package]
name = "gist"
version = "0.1.0"
edition = "2021"

[dependencies]
msg = { path = "../msg" }
curl = { version = "0.4", features = ["http2"] }
anyhow = "1.0"
serde_json = "1.0.86"
json = "0.12.4"